[build]
builder = "NIXPACKS"
buildCommand = "pnpm install"

[deploy]
startCommand = "pnpm start --character=\"characters/sage.character.json\""
// healthcheckPath = "/health"
// healthcheckTimeout = 100
// restartPolicyType = "ON_FAILURE"
// restartPolicyMaxRetries = 5

[deploy.envs]
NODE_ENV = "production"